### ISSUE TITLE
Bug with Google Maps plug-in

### ISSUE THREAD

**Issue by michgagnon** [ZenPhoto20/ZenPhoto20#474] opened 2016-01-03 01:49 UTC
Hello,

I have developed the same gallery in Zenphoto20 and (to a point) in Zenphoto. This has allowed me to see that the Google Maps plugin works perfectly in Zenphoto with the Zenpage theme. Alas, it does not work in Zenphoto20. With all standard themes such as Zenpage, I see a map, but points are not placed properly. With the zpSkeleton theme, The map doesn't show up. I see a grey rectangle instead.

Here are screen captures and the location in Google maps:
– With Zenphoto (the other one)
(map location: https://goo.gl/maps/L52BB6D7XSR2 – the good one)
![googlemapwithzenphotozenpage](https://cloud.githubusercontent.com/assets/2497527/12076903/bf64fece-b18e-11e5-944f-22de2a737e86.png)

– With Zenphoto20
(map location: https://goo.gl/maps/NNojU2kyHJ12)
![googlemapswithzenphoto20zenpage](https://cloud.githubusercontent.com/assets/2497527/12076905/d7f66cde-b18e-11e5-9ebe-82f91e0dacfe.png)

Or see it online, with the zpBootstrap theme at http://mgagnon.net/photos/fresquesurbaines/

To see the distance between both points: https://goo.gl/maps/woadzzQjXFK2

Thank you.

P.S. I generally find Zenphoto20 more flexible and in "better shape" than its predecessor.

**Comment by michgagnon** [comment] 2016-01-03 05:01
I ticked on all EXIF parameters in the Options –> Image page and downloaded the complete EXIF parameters for this photo:http://mgagnon.net/photos/fresquesurbaines/DSD_3534.jpg.html. 
Here they are:

**With Zenphoto**
```
Camera Maker:		Nikon Corporation
Camera Model:		NIKON D7100
Original Time Taken: 2015-06-20
Time Digitized:      2015-06-20
Artist:				Michel Gagnon
Byline:				Michel Gagnon
Copyright Holder:	Michel Gagnon
Copyright Notice:	Michel Gagnon
Shutter Speed:		1/125 sec
Aperture:			f/5,6
ISO Sensitivity:	160
Exposure Compensation:	0,67 EV
Metering Mode:		Center Weighted Average
Flash Fired:		No Flash
Original Width:		6000 pixels
Original Height:	4000 pixels
Orientation:		1: Normal (0 deg)
Software:			Ver.1.02
Focal Length:		50 mm
Lens Type:			AF-D G VR
Lens Info:			17-50mm f/2,8
35mm Focal Length Equivalent: 75
City:				Montréal
Sub-location:		Ville-Marie (rue Ontario Est)
Province/State:		Quebec
Country/Primary Location Code:	CAN
Country/Primary Location Name:	Canada
Latitude:			45,512624990001
Latitude Reference:	 N
Longitude:			73,566169739953
Longitude Reference: W
Altitude:			27m
Altitude Reference:	+
``` 

**With ZenPhoto20**
```
35mm Focal Length Equivalent:	75
Altitude:				27m
Aperture:				f/5,6
Artist:					Michel Gagnon
Byline:					Michel Gagnon
Camera Maker:			Nikon Corporation
Camera Model:			NIKON D7100
City:					Montréal
Copyright Holder:		Michel Gagnon
Copyright Notice:		Michel Gagnon
Country/Primary Location Code:	CAN
Country/Primary Location Name:	Canada
Date Created:			1969-12-31
Digital Creation Date:	1969-12-31
Digital Creation Time:	1969-12-31
Exposure Compensation:	0,67 EV
Exposure time:			1/125 sec
Flash Fired:			No Flash
Focal Length:			50 mm
ISO Sensitivity:		160
Latitude:				45° 0' 0" N  (Wrong value)
Lens Info:				17-50mm f/2,8
Lens Type:				AF-D G VR
Longitude:				73° 0' 0" W (wrong value)
Metering Mode:			Center Weighted Average
Orientation:			Normal (0 deg)
Original Height:		4000 pixels
Original Time Taken:	2015-06-20
Original Width:			6000 pixels
Province/State:			Quebec
Software:				Ver.1.02
Sub-location:			Ville-Marie (rue Ontario Est)
Time Created:			1969-12-31
Time Digitized:			2015-06-20
```

When I compare with the complete Exif data (extracted with ExifToolGUI), I see the following differences:
```
Date Created 			2015-06-20 14:52:53-0400 (Eastern Daylight Savings Time)
Digital Creation Date: 	2015-06-20 14:52:53-0400
Digital Creation Time: 	2015-06-20 14:52:53-0400
Time Created: 			2015-06-20 14:52:53-0400
Time Digitized: 		2015-06-20 14:52:53-0400
Latitude: 				45.512625 N
Longitude: 				73.566170 W

Information missing: some indication whether we are above or below sea level (ex.: Death Valley)
GPSAltitudeRef: Above Sea Level

**Comment by Mates-K1** [comment] 2016-01-03 10:28
I think it is related to #363.
Now I check how ZP20 (1.2.3.1) shows my GPS - in map it is OK, but ZP20 shows 16° 0' 0" E, 50° 0' 0" N (right is 16° 29' 49" E, 50° 10' 34" N).

**Comment by sbillard** [comment] 2016-01-03 17:18
could you please attach the original image that has the problem. This is normally caused by number conversion problems (e.g. the comma not being treated as a decimal point.) I may need  you to insert some debug code as your locale may also be involved in the issue.

**Comment by Mates-K1** [comment] 2016-01-03 19:06
Metadata refreshed twice.

It shows wrong values anywhere in ZP20 except googlemaps.

Wrong coordinates are in:
- frontend - for ex. Garland or Zenpage theme in image information,
- backend - image information.

Zenpage theme:
![01](https://cloud.githubusercontent.com/assets/7648991/12080242/018ac24a-b255-11e5-9d09-d24caf8d6a03.jpg)

Editing img information:
![02](https://cloud.githubusercontent.com/assets/7648991/12080243/06365868-b255-11e5-849e-1f484bbc5840.jpg)

Sample foto:
![001](https://cloud.githubusercontent.com/assets/7648991/12080244/08ac7942-b255-11e5-86e8-66c2968b71f6.jpg)

**Comment by michgagnon** [comment] 2016-01-03 21:50
Hello,

I am not able to upload my photo (the one I was talking about in the first message) as it is too large for Github and I don't want to compress it for fear of tainting the data. So here is a direct link to the file, outside of Zenphoto20: http://mgagnon.net/fichiers/DSD_3534.jpg or  http://mgagnon.net/fichiers/DSD_3534.zip

Interesting bit of information:

Real data: 
Latitude:     45.512625 N
Longitude:  73.566170 W

Data as posted by ZenPhoto20 in Exif:
Latitude:    45° 0’ 0” N
Longitude: 73° 0’ 0” W

Data as pointed on the map:
Latitude:     45.512625 N
Longitude:  73.000000 N

So, apart from finding where is the bug and correcting it, my suggestion would be to keep the latitude and longitude in decimal degrees (i.e. 45.51264 N, 73.5662 W)

Regards,

Michel

**Comment by sbillard** [comment] 2016-01-04 03:03
Note that the fix will require a metadata refresh as the incorrect value is stored in the database.

There were two problems present. The incorrect display of the GPS data was caused by a PHP quirk on working with numeric strings. With the locale set to FR_fr numeric strings use a comma as a decimal separator. However when the same string was "floated" to be used in math computations the conversion treated the comma as the end of the number. The fix for this was to brute force "float" the number handling either comma or period as the decimal separator.

The second problem was similar, but involved the negation of the number. In this case because the latitude was West. (This would also have failed for countries below the equator.)

Neither issue really had anything to do with how the values are kept. The GPSxxxx fields are kept as floating point numbers as you suggest. They are converted for display. The image did work for me when the metadata was for EN_us.

**Closed** 2016-01-04 03:04 UTC

**Comment by michgagnon** [comment] 2016-01-04 05:31
I'm sorry, but it doesn't work
