### ISSUE TITLE
News article creation vs. group editing permissions

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#709] opened 2018-01-17 18:55 UTC
When a usergroup does not have editing rights to a news article category, they should not be able to create an article. By going to the News section on the admin drop down they are still able to create news. This should have the same behavior as for albums. Also the settings in the group for categories seem to dissapear repeatedly, but I am not sure how.

**Comment by sbillard** [comment] 2018-01-18 20:08
[setup-1.5.2.20.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1644279/setup-1.5.2.20.zip)

Could you please try this release to see ifit solves your issue.

**Comment by Elinth** [comment] 2018-01-19 09:07
That's quick! Thank you so much!
That works well. Just need to test see if the settings remain. This was a
problem in the previous set up.

Cheers

Eddie

**Comment by Elinth** [comment] 2018-01-19 09:42
Hi Stephen,

There is I think one more bug. As an admin my news article list is empty.
I cannot edit create or delete any news articles.

Cheers

Ewoud

**Comment by Elinth** [comment] 2018-01-19 09:57
Also the news.php is unreachable and showing 3 php errors:  Warning: "Cannot modify header information"

**Comment by sbillard** [comment] 2018-01-19 17:02
Can you provide some more details? I do not think I am seeing this.

You are talking about when you are logged in as a full rights administrator? What do you mean by "my news list"? Is that a list by author?

**Comment by sbillard** [comment] 2018-01-19 17:05
You also said in an email 'Also the news.php is unreachable and showing 3 php errors: Warning: "Cannot modify header information"' I would need to see all the PHP errors. "Cannot modify header information" is a down-stream effect of some other issue, most likely a different error.

Also, please try to use the ticket system when responding so that all the discussion is tracked.

**Comment by Elinth** [comment] 2018-01-20 08:51
Hi Stephen, Sorry, I have to get used to this ticketing system. The 3 php errors I resolved by renewing the theme to the one you have in the build you send me. I was using an older tweaked version of ZPArdoise. This was throwing errors on the news.php page. 
Your changes work really well, the only thing is when I go to the admin toolkit and click on news. The news articles are not displayed. This is when I am logged in as administrator that has full rights.  The news is displayed on the news.php correctly and in cases of group assignments the behavior works as expected that users can only see what to what category they are assigned to.

**Comment by sbillard** [comment] 2018-01-20 16:39
The ticketing system does take some getting  used to. But it is really useful for keeping track of an issue.

Glad the errors are gone. Now we just have to figure what is causing your remaining problem. Since I am not seeing anything like what you describe we need to get down to the details.

What should be happening when you click on the news link from the toolbox is that you are taken to the zp-core/zp-extensions/zenpage/admin-news.php link. Does that happen? What is shown on the page?

What happens if you are on the admin overview page and select the news articles link? Is it different from what happens from the toolbox link?

Are all your articles assigned to categories? Are the articles published or not published?

**Comment by Elinth** [comment] 2018-01-21 15:15
I think I figured it out. It is more simple then I thought.. When I am in news via the admin toolbox or in news via admin overview page everything seems normal. I am taken to the zp-core/zp-extensions/zenpage/admin-news.php. What I just noticed is that all my news articles are unpublished. If I select unpublished items it shows my content. When I select all content it does not show anything. I think this is the small bug. When you select all content it shows only the published content, while I think it should show both published and unpublished content.

**Comment by sbillard** [comment] 2018-01-21 17:39
Thanks much, I can reproduce this, so I will figure it out.

**Comment by sbillard** [comment] 2018-01-21 18:03
This should fix the issue. Pleasse verify.
[setup-1.5.2.21.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1650007/setup-1.5.2.21.zip)

**Comment by Elinth** [comment] 2018-01-21 18:35
Worked like a charm! Thank you, you are a genius!
Maybe I am asking to much but it would be a nice feature or plugin request to have email notifications for news articles, maybe even per category. I thought.. I can always ask... :-)

**Comment by Elinth** [comment] 2018-01-21 19:05
Strange, somehow my contact page on my password.php page stopped working after this setup. It only shows a part of the the header. When I am logged in as admin it does show the full form.

**Comment by Elinth** [comment] 2018-01-21 19:37
To be more specific, I have a menu link (from the menu in inc_header.php) that allows users to go to the contact.php page. When a user is logged in the contact form on the contac.php page displays well. When the user is not logged in it shows only a small part of the header of the contact.php page and the form is not displayed. I have the contact.php page set up as a unprotected page in the galery options.

**Comment by sbillard** [comment] 2018-01-22 00:24
I have tried this with the version of zpArdoise that is part of the release and do not see any issues. Your link should read "http://<site>/page/contact" in both cases, is this the case?

Have you tried this with any of the other themes?

At any case there should be a new issue created for this problem as it is not related to the original issue of this thread and this issue will become closed as soon as I update the main repository with the fix. (Github will do this automatically.)

**Closed** 2018-01-22 00:25 UTC
