### ISSUE TITLE
Fresh install of 1.5.0.1 (or 1.4.3.4d8 or d10) - cant change language

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#646] opened 2017-09-21 21:46 UTC
I have two domains from same provider. In one domain there is latest stable - 1.5.0.1 - and works normally (except first set_time_limit warning - this is the same).

When I try to install fresh install on second domain, when files are extracted I get:
![untitled 1](https://user-images.githubusercontent.com/7648991/30719581-52197a68-9f24-11e7-948d-7e71164d786f.jpg)
and
![d4e4e2a4-590d-41ab-8b9a-50cbdd1b4e5b](https://user-images.githubusercontent.com/7648991/30719781-1ed78004-9f25-11e7-95d2-fce03b26f9d7.png)
but setup can run and is in english, I cant swith langages by clicking on icons - it does nothing.

When I set new admin, his language, in admin tab in Current locale setting is **C** (simply uppercase C).
![77306478-8261-46f6-ab3e-144c2bb1ae52](https://user-images.githubusercontent.com/7648991/30719873-98a5dc14-9f25-11e7-91e2-7957946de49d.png)
(there is another font use for **PHP GD library bundled (2.1.0 compatible)** text)

Debug log:
```
{34787:Thu, 21 Sep 2017 21:18:15 GMT} ZenPhoto20 v1.5.0.1
  WARNING: "system() has been disabled for security reasons" in /data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/debug/admin_tab.php on line 276
 URI:/zp-core/zp-extensions/debug/admin_tab.php?page=develpment&tab=locale

  system called from admin_tab.php [276]
{34787:Thu, 21 Sep 2017 21:18:15 GMT}
  WARNING: "system() has been disabled for security reasons" in /data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/debug/admin_tab.php on line 276
 URI:/zp-core/zp-extensions/debug/admin_tab.php?page=develpment&tab=locale

  zpShutDownFunction called from unknown
{35853:Thu, 21 Sep 2017 21:37:42 GMT}
  WARNING: "system() has been disabled for security reasons" in /data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/debug/admin_tab.php on line 276
 URI:/zp-core/zp-extensions/debug/admin_tab.php?page=develpment&tab=locale

  system called from admin_tab.php [276]
{35853:Thu, 21 Sep 2017 21:37:42 GMT}
  WARNING: "system() has been disabled for security reasons" in /data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/debug/admin_tab.php on line 276
 URI:/zp-core/zp-extensions/debug/admin_tab.php?page=develpment&tab=locale

  zpShutDownFunction called from unknown
```

**Comment by sbillard** [comment] 2017-09-21 23:00
The warnings you are getting are "security" constraints placed by your hosting provider. Who knows why. 

The first prevents the _extract.php_ script from insuring that the script timer does not run out on it. So long as the extract works, this is not really a problem.

The "_system()_" one is preventing the _debug_ plugin from requesting the supported locales from the server. So we do not know what locales are configured. But if you cannot select a language it is most likely caused by the server not having that language configured. The locale being "C" would probably mean that the only language set supported is the "C" programming language one.

The sessions issue may be the result of the tightening up of ZenPhoto20 Session and cookie handling. Specially if this  happens with Chrome and not FireFox. Chrome seems not to properly delete cookies when it should. Then to compound this it grabs the wrong one if there are multiples. Clearing its browser data usually solves this, but mostly I just switch to FireFox when I see the error.

Anyway, ask your provider what is configured differently between the two sites. Specially with regards to security policy and language support.

**Comment by sbillard** [comment] 2017-09-22 00:28
IT occurs to me that we might learn something by setting the _debug_ plugin option "Log language selection processing."

**Comment by Mates-K1** [comment] 2017-09-22 12:52
Debug log says nothing - it is simply clean.

From provider: According to the list of enabled features, "system" is in the disabled, "disabled_functions". This can not be changed.

**Comment by sbillard** [comment] 2017-09-22 15:37
Log was clean after enabling the "log language selection processing?" Be sure the release is marked as a debug release on the overview page. If not use the mark release button to make it so.

The system restriction is probably not a problem. I'm pretty sure it is used only to list the supported languages. (Of course that is exactly what we need to know in this case.)

**Comment by Mates-K1** [comment] 2017-09-22 17:57
Sorry, my stupidity. One change from Czech to Danish:
```
{40892:Fri, 22 Sep 2017 17:53:44 GMT} ZenPhoto20 v1.5.0.1-DEBUG_LOCALE,
  setMainDomain()
 URI:/zp-core/admin-options.php?page=options&tab=general
 IP `185.19.2.51`
  setMainDomain called from require_once (functions.php [29])
    from require_once (admin-functions.php [11])
      from require_once (admin-globals.php [16])
        from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  validateLocale(skautskagalerie,HTTP_HOST)
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  dynamic_locale from HTTP_HOST: skautskagalerie=>
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  locale from option: cs_CZ; dynamic locale=
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  getUserLocale Returning locale: cs_CZ
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  setlocale(cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs,) returned: C
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  setupCurrentLocale(cs_CZ): locale=cs_CZ, $result=C
 URI:/zp-core/admin-options.php?page=options&tab=general
 IP `185.19.2.51`
  setupCurrentLocale called from setMainDomain (functions-i18n.php [502])
    from require_once (functions.php [29])
      from require_once (admin-functions.php [11])
        from require_once (admin-globals.php [16])
          from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  setlocale(cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs,) returned: C
{40892:Fri, 22 Sep 2017 17:53:44 GMT}
  setupCurrentLocale(cs_CZ): locale=cs_CZ, $result=C
 URI:/zp-core/admin-options.php?page=options&tab=general
 IP `185.19.2.51`
 user:Mates
  setupCurrentLocale called from require_once (auth_zp.php [86])
    from require_once (load_objectClasses.php [46])
      from require_once (functions.php [31])
        from require_once (admin-functions.php [11])
          from require_once (admin-globals.php [16])
            from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setMainDomain()
 URI:/zp-core/admin-options.php?action=saveoptions
 IP `185.19.2.51`
  setMainDomain called from require_once (functions.php [29])
    from require_once (admin-functions.php [11])
      from require_once (admin-globals.php [16])
        from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  validateLocale(da_DK,POST)
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  locale set from POST: da_DK
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  dynamic_locale from URL: da_DK=>da_DK
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  getUserLocale Returning locale: da_DK
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setlocale(da_DK.UTF8,da_DK.UTF-8,da_DK.@euro,da_DK,da,) returned: C
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setupCurrentLocale(da_DK): locale=da_DK, $result=C
 URI:/zp-core/admin-options.php?action=saveoptions
 IP `185.19.2.51`
  setupCurrentLocale called from setMainDomain (functions-i18n.php [502])
    from require_once (functions.php [29])
      from require_once (admin-functions.php [11])
        from require_once (admin-globals.php [16])
          from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setlocale(cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs,) returned: C
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setupCurrentLocale(cs_CZ): locale=cs_CZ, $result=C
 URI:/zp-core/admin-options.php?action=saveoptions
 IP `185.19.2.51`
 user:Mates
  setupCurrentLocale called from require_once (auth_zp.php [86])
    from require_once (load_objectClasses.php [46])
      from require_once (functions.php [31])
        from require_once (admin-functions.php [11])
          from require_once (admin-globals.php [16])
            from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setlocale(da_DK.UTF8,da_DK.UTF-8,da_DK.@euro,da_DK,da,) returned: C
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setMainDomain()
 URI:/zp-core/admin-options.php?saved&tab=general
 IP `185.19.2.51`
  setMainDomain called from require_once (functions.php [29])
    from require_once (admin-functions.php [11])
      from require_once (admin-globals.php [16])
        from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  validateLocale(skautskagalerie,HTTP_HOST)
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  dynamic_locale from HTTP_HOST: skautskagalerie=>
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  locale from option: da_DK; dynamic locale=
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  getUserLocale Returning locale: da_DK
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setlocale(da_DK.UTF8,da_DK.UTF-8,da_DK.@euro,da_DK,da,) returned: C
{40892:Fri, 22 Sep 2017 17:53:48 GMT}
  setupCurrentLocale(da_DK): locale=da_DK, $result=C
 URI:/zp-core/admin-options.php?saved&tab=general
 IP `185.19.2.51`
  setupCurrentLocale called from setMainDomain (functions-i18n.php [502])
    from require_once (functions.php [29])
      from require_once (admin-functions.php [11])
        from require_once (admin-globals.php [16])
          from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:49 GMT}
  setlocale(cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs,) returned: C
{40892:Fri, 22 Sep 2017 17:53:49 GMT}
  setupCurrentLocale(cs_CZ): locale=cs_CZ, $result=C
 URI:/zp-core/admin-options.php?saved&tab=general
 IP `185.19.2.51`
 user:Mates
  setupCurrentLocale called from require_once (auth_zp.php [86])
    from require_once (load_objectClasses.php [46])
      from require_once (functions.php [31])
        from require_once (admin-functions.php [11])
          from require_once (admin-globals.php [16])
            from admin-options.php [12]
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  setMainDomain()
 URI:/zp-core/admin-logs.php?page=logs&tab=debug
 IP `185.19.2.51`
  setMainDomain called from require_once (functions.php [29])
    from require_once (admin-functions.php [11])
      from require_once (admin-globals.php [16])
        from admin-logs.php [10]
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  validateLocale(skautskagalerie,HTTP_HOST)
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  dynamic_locale from HTTP_HOST: skautskagalerie=>
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  locale from option: da_DK; dynamic locale=
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  getUserLocale Returning locale: da_DK
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  setlocale(da_DK.UTF8,da_DK.UTF-8,da_DK.@euro,da_DK,da,) returned: C
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  setupCurrentLocale(da_DK): locale=da_DK, $result=C
 URI:/zp-core/admin-logs.php?page=logs&tab=debug
 IP `185.19.2.51`
  setupCurrentLocale called from setMainDomain (functions-i18n.php [502])
    from require_once (functions.php [29])
      from require_once (admin-functions.php [11])
        from require_once (admin-globals.php [16])
          from admin-logs.php [10]
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  setlocale(cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs,) returned: C
{40892:Fri, 22 Sep 2017 17:53:52 GMT}
  setupCurrentLocale(cs_CZ): locale=cs_CZ, $result=C
 URI:/zp-core/admin-logs.php?page=logs&tab=debug
 IP `185.19.2.51`
 user:Mates
  setupCurrentLocale called from require_once (auth_zp.php [86])
    from require_once (load_objectClasses.php [46])
      from require_once (functions.php [31])
        from require_once (admin-functions.php [11])
          from require_once (admin-globals.php [16])
            from admin-logs.php [10]
```

**Comment by Mates-K1** [comment] 2017-09-22 19:42
And another warning from edit img page:
![38d3be35-ee6c-45b8-8e97-9d933255fd3a](https://user-images.githubusercontent.com/7648991/30761542-e5f5cd62-9fde-11e7-8f67-ac0cf7b919ad.png)

**Comment by Mates-K1** [comment] 2017-09-22 19:48
The only thing that changes correctly when changing language is "My Favorites" on main frontend page.

**Comment by sbillard** [comment] 2017-09-23 00:32
So what this tells us is that your server is not setting the locale. We pass the PHP setlocale() function a list of local options. For Czech the list is "cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs," and none of them match a local that your server is supporting. Instead it is returning "C" as the current locale, so one would presume that "C" is all that is supported.

I don't know why "My Favorites" would actually work, though. Nothing should be being translated.

Anyway, show your hoster the lines that show what we passed setlocale() and what it returned--"C". If they are not believers, set the same debug option on the site that works and show them the results.

**Comment by Mates-K1** [comment] 2017-09-23 11:48
+ another warning when logging in (simply blank screen and this text), F5 helps (Vivaldi and Firefox).

Warning: Cookie names cannot contain any of the following '=,; \t\r\n\013\014' in /data/............/zp-core/functions-common.php on line 698

Warning: Cannot modify header information - headers already sent by (output started at /data/................./galerie/zp-core/functions-common.php:698) in /data/............/zp-core/auth_zp.php on line 60

**Comment by sbillard** [comment] 2017-09-23 19:20
There is a superfluous comma on the LANGUAGE option that is causing this error. It will be fixed in the next update, but for now just uncheck the Log Language Selection option. We probably have enough information for your host provider to fix his issue.

**Comment by sbillard** [comment] 2017-09-23 20:21
[setup-1.5.0.3.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1326831/setup-1.5.0.3.zip)

This has the changes discussed

**Comment by Mates-K1** [comment] 2017-09-24 17:07
Provider:
Unfortunately, I do not know where the problem might be. This seems to bug in your web application.


I tried HTTP_Accept_Language and there is "CS_CZ" value (uppercase)- can it help?
```
{31816:Sun, 24 Sep 2017 17:00:09 GMT}
  validateLocale(CS_CZ,HTTP Accept Language)
{31816:Sun, 24 Sep 2017 17:00:09 GMT}
  locale set from HTTP Accept Language: cs_CZ
{31816:Sun, 24 Sep 2017 17:00:09 GMT}
  getUserLocale Returning locale: cs_CZ
{31816:Sun, 24 Sep 2017 17:00:09 GMT}
  setlocale(cs_CZ.UTF8,cs_CZ.UTF-8,cs_CZ.@euro,cs_CZ,cs,) returned: C
```

**Comment by sbillard** [comment] 2017-09-24 17:32
These locales are supposed to be case insensitive, but maybe it would help. You can try changing line 364 of functions-i18n.php to `$rslt = setlocale(LC_ALL, strtoupper($try));` and see what happens. But I doubt it will make any difference.

You did say that you have an installation with that provider that does work correctly, didn't you?

What we really need is to know what locales the provider does support. We could know that except for the "system()" restriction that they have instituted. Anyway, if you have a site that works, set the LANGUAGE logging option on it and get the comparison.  If you can show the provider both the working and the not working debug logs he cannot claim that the problem is with the software.

But the short answer is that the provider is not correct and apparently not knowledgeable. 

See http://php.net/manual/en/function.setlocale.php for the `setlocale()` function. You will note that it states "The return value of setlocale() depends on the system that PHP is running. It returns exactly what the system setlocale function returns." As it is returning "C" rather than a Czech locale then the translations will not work.

**Comment by Mates-K1** [comment] 2017-09-26 07:55
> These locales are supposed to be case insensitive, but maybe it would help. You can try changing line 364 of functions-i18n.php to $rslt = setlocale(LC_ALL, strtoupper($try)); and see what happens. But I doubt it will make any difference.

Does nothing.

For the third attempt, I've reached the point of waiting to contacting someone from extended support for CMS. None of these three previous people knew where a problem or mistake could be, all of them blame ZenPhoto20.

So now I am waiting. Gallery works - only in English.
Thanks for support.

**Comment by sbillard** [comment] 2017-09-26 15:43
So the provider does not understand when you tell him that one of your domains works and the other does not? Same software on both?

**Comment by Mates-K1** [comment] 2017-10-02 17:36
Yes, he knows that. He has both logs.

After 5 days of waiting:

> Hello,
> unfortunately in this case I do not know how to help, I'm sorry.
> Would Apache errorlog and accesslog help you?

:/

**Comment by sbillard** [comment] 2017-10-02 18:13
I doubt that the logs will help, but it is worth a try. But we need them to help us with this. Wading through hundreds of log entries would be difficult. If they can clear the logs, then access the site and try to change languages then the log immediately after that would be something that might be possible to analyze.

Of course, since this is really probably an Apache configuration issue the hosting service is SUPPOSED to be the experts on this, not us.

**Comment by sbillard** [comment] 2017-10-03 21:20
The attached release may be of some help to you. I have implemented a fall-back to the PHP gettext module. This may bypass the server issue you are having.

Install this release then go to your PHP.ini file and edit the line that reads extension=php_gettext.dll by adding a semicolon (;) to the front of the line. This will cause ZenPhoto20 to use the alternate translation facility.

[setup-1.5.0.11.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1353930/setup-1.5.0.11.zip)

**Comment by sbillard** [comment] 2017-10-04 21:43
It occurs to me that there will still be one problem even with the alternate translations facility. Numbers will probably be represented as in the US, with periods as the decimal separator. That is another thing that is controlled by the locale. Nothing that I can think of to do about that since the number formatting is done within PHP and relies on knowing the locale to know how to represent decimal numbers.

**Comment by Mates-K1** [comment] 2017-10-05 06:16
Unfortunately, I cant change PHP.ini this way, I can only set on/off to:
![3ddf05dc-fa06-4f76-aeb7-23802217d8f8](https://user-images.githubusercontent.com/7648991/31213011-4d161ea6-a9a4-11e7-81c2-cc175dc8d403.png)

But... I dont know how... **Language setting now works...** 👍 I upgraded from 1.5.0.3 to 1.5.0.10 - so this didnt help. After cca two days of rest... it works.

I dont know if provider did some change, but the latest suggestion of solution was create completely new webhosting space and reconnect it back to domain. 

**Thank you very much for your help and support - I appreciate it.**

**Comment by sbillard** [comment] 2017-10-05 17:12
Glad at least that things now work. I'll close the issue now.

**Closed by sbillard** 2017-10-05 17:12 UTC
