### ISSUE TITLE
jPlayer

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#643] opened 2017-09-14 06:35 UTC
When I first wanted to look into the gallery after the 500 error problems, I got a message (this is from log):

`[Wed Sep 13 20:23:26.335523 2017] [:error] [pid 4945] [client 62.204.231.182:4263] FastCGI: server "/var/www/clients/client33/web242/cgi-bin/php5-fcgi-*-80-skaut.zamberk.cz" stderr: PHP message: PHP Fatal error:  Cannot redeclare printjPlayerPlaylist() (previously declared in /var/www/clients/client33/web242/web/galerieonline/zp-core/zp-extensions/jplayer.php:96) in /var/www/clients/client33/web242/web/galerieonline/zp-core/zp-extensions/jPlayer.php on line 96, referer: http://skaut.zamberk.cz/galerieonline/zp-core/setup/index.php?checked&update&autorun%20=%20admin&mod_rewrite=ON`

I noticed a difference in the size of the letters in the file jplayer.php and at plugin directory, I found that I have both directories in instalation (1.4.3.4 has lower case, latest build has upper case). Now I'm not seeing skin players (uppercase, in lowercase is wrongly aligned), videos can not be played (MP4) and there arent thumbs of videos on image or album pages (neither placeholders nor my thumbs).

**Comment by sbillard** [comment] 2017-09-14 16:51
Setup should have reported extra files and offered to delete the lower case ones for you. Did that happen?

**Comment by Mates-K1** [comment] 2017-09-14 19:22
Hmmm.... I deleted old jPlayer file manually.

Honestly ... I do not like this delete feature very much because it always deletes my custom header from theme. :( I only do that by official way - upload header img file to images folder of my theme, but every update delete this file.

But... in latest build in jPlayer.php there is 9x path to player folder in lower case... When I repaire that manually everything works.

**Comment by sbillard** [comment] 2017-09-14 21:25
Well, you really should be making a copy of the distributed theme and modifying that version. 

This should be fixed in by c4f4ee4ca4f41bfd8d1a0d2d60d2b48e2dbcf665

**Comment by sbillard** [comment] 2017-09-15 22:00
[setup-1.4.3.4d11.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1307822/setup-1.4.3.4d11.zip)

Fixes the file names. Also prevents fatal PHP errors caused by loading both plugin versions and reports any other errors a plugin gets into the Setup log.

**Comment by Mates-K1** [comment] 2017-09-16 08:10
It seems to work. Thanks as ever. :)

**Closed** 2017-09-22 00:25 UTC
