### ISSUE TITLE
Settings for news category groups keep resetting

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/ZenPhoto20#715] opened 2018-01-25 16:18 UTC
Somehow the newly created news category settings per user group keep dissapearing after a day or two. I cannot seem to find what is causing this but I keep having to re-do the settings.

**Comment by sbillard** [comment] 2018-01-25 17:24
Can you be more specific?

What are the settings before and after the disappearing? 

What in general is happening in these day or two intervals?

Can you narrow down the time frame? Do they disappear overnight, for instance?  It will be really hard to diagnose this without narrowing down the situation.

**Comment by Elinth** [comment] 2018-01-25 17:42
Sorry for my vague explanation. I keep having to set my group rights for news categories. As an admin I can always see the news and all categories but when I give a user group viewing rights the next day or after some days the tick boxes are unticked again and it shows no managed news categories. It kind of seems that the database overwrites these settings. Hard to say what the timeframe is when this happens. I just made some test settings to see if the how long it takes for the database to forget the group rights settings for news. Strange isn't it?

**Comment by sbillard** [comment] 2018-01-25 17:47
Ok, I understand. But I have no idea what might cause that. These settings are stored in the database so should be persistent. Does anything else get forgotten?

**Comment by Elinth** [comment] 2018-01-25 18:16
Nope just these news settings. Maybe its my fault... I did put news on my gallery.php page, see below how I did this. Could this code be interfering?

I used the following code on my gallery.php:
<?php include('inc_print_news_loop.php'); ?> 

and this on the inc_print_news_loop.php:

<?php // news article loop ?>
<div id="headline-news"><hr><center><h2><?php echo gettext('News'); ?></h2> </center></hr>
			<?php if (is_NewsArticle()) { ?> 
			<div class="control-nav-news">
				<div class="nav-img clearfix">
					<ul class="clearfix">
					<?php if (getPrevNewsURL()) { ?>
						<li><a href="<?php $article_url = getPrevNewsURL(); echo $article_url['link']; ?>" title="<?php echo $article_url['title']; ?>">&laquo; <?php echo gettext('newer'); ?></a></li>
					<?php } else { ?>
						<li class="disabledlink"><span>&laquo; <?php echo gettext('newer'); ?></span></li>
					<?php } ?>
					<?php if (getNextNewsURL()) { ?>
						<li><a href="<?php $article_url = getNextNewsURL(); echo $article_url['link']; ?>" title="<?php echo $article_url['title']; ?>"><?php echo gettext('older'); ?> &raquo;</a></li>
					<?php } else { ?>
						<li class="disabledlink"><span><?php echo gettext('older'); ?> &raquo;</span></li>
					<?php } ?>
					</ul>
				</div>
			</div>
			
			<?php } else { ?>
			<div class="news-cat-list">
				
			</div>
			<?php } ?>
	
		</div>

	<?php
	// single news article
	if (is_NewsArticle()) { ?>
		<div id="news" class="clearfix">
			<h3><?php printNewsTitle(); ?></h3>
			<div class="newsarticlecredit">
				<?php printNewsDate(); ?><?php printNewsCategories(', ', gettext(' | '), 'hor-list'); ?>
			</div>
			<?php if (getNewsExtraContent()) { ?>
			<div class="extra-content clearfix">
				<?php printNewsExtraContent(); ?>
			</div>
			<?php } ?>
			<div class="clearfix">
				<?php printNewsContent(); ?>
				<?php printCodeblock(1); ?>
			</div>
			<?php if (getOption('show_tag')) { ?>
				<div class="headline-tags"><?php printTags('links', '', 'hor-list'); ?></div>
			<?php } ?>
		</div>

		<?php if (extensionEnabled('comment_form')) { ?>
			<?php include('inc_print_comment.php'); ?>
		<?php } ?>

	<?php } else {
	// news article loop ?>

		<div class="pagination-news clearfix">
			<?php printNewsPageListWithNav(' » ', ' « ', true, 'clearfix'); ?>
		</div>

		<div id="news" class="clearfix">
			<?php while (next_news()) { ?>
			<div class="news-truncate clearfix">
				<h3><?php printNewsURL(); ?></h3>
				<div class="newsarticlecredit">
					<?php printNewsDate(); ?><?php printNewsCategories(', ', ' | ', 'hor-list'); ?>
				</div>

				<?php printNewsContent(false, '<p class="readmorelink">(...)</p>'); ?>

			</div>
			<?php } ?>
		</div>

		<div class="pagination-news clearfix">
			<?php printNewsPageListWithNav(' » ', ' « ', true, 'clearfix'); ?>
		</div>

	<?php } ?>

**Comment by Elinth** [comment] 2018-01-25 18:26
I cannot seem to correctly display the code here. I'll email it to you.

**Comment by sbillard** [comment] 2018-01-25 20:56
The code has shown up fine here. I assume that this is to display a list of news excerpts on your gallery home page. If so, the part associated with "single news article" is not needed, but would not be a problem.

Nothing in this code should be changing any saved settings. So something else must be happening. DO you have more than one group with managed news categories? If so do all groups loose the settings?

**Comment by Elinth** [comment] 2018-01-25 21:20
Yes, I have 6 groups. None of them have editing rights for news articles, they only have viewing unpublished item rights for 8 newscategories (depending on the group). All the unpublished item right settings for newscategories for 6 groups are cleared. 
I actually have the same settings for these 6 groups for unpublished albums. These settings remain as is. So the behavior is only with the news items.

**Comment by sbillard** [comment] 2018-01-25 22:12
are the users in more than one group?

**Comment by Elinth** [comment] 2018-01-25 22:43
Nope. The users are in only one group. Yes, each group has a set of 8 managed categories, all of which have Edit unchecked and view unpublished checked. The general "News" rights (If you mean the tick-box to the left of the category name) is checked for the 8 categories.  The boxes: Access all, View unpublished, Manage all, are unchecked.

**Comment by sbillard** [comment] 2018-01-26 00:38
Thanks for the details. I've setup an equivalent group. So far everything is remembered.

Does the general checkbox for the categories stay checked? That is just the view unpublished gets unchecked?

**Comment by Elinth** [comment] 2018-01-26 10:22
My test settings are also still there. The general checkbox does not get remembered too when this happens.

**Comment by sbillard** [comment] 2018-01-26 16:31
So the issue is that the managed objects as a whole are not being remembered. Can you create a simple user and set his managed objects as for the group and see if they stick?

Have you had any lick in narrowing down the window on this?

**Comment by Elinth** [comment] 2018-01-29 09:29
I have created a test user last week. Strangely enough it is not overwriting it yet. I'll keep an eye on it.

**Comment by sbillard** [comment] 2018-01-29 16:44
Thanks for the update.

**Comment by Elinth** [comment] 2018-02-01 09:15
Once I updated to 1.5.3.01. The settings are gone for my test user.

**Comment by sbillard** [comment] 2018-02-01 20:22
Please copy this version of lib-auth.php over the distributed one. It will log whenever the rights settings are changed and hopefully tell us when and where the change happened.

[lib-auth.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1687081/lib-auth.zip)

**Comment by Elinth** [comment] 2018-02-01 20:31
Do I need to run setup again? It says Zenphoto detected a change in the file etc.

**Comment by sbillard** [comment] 2018-02-01 21:44
You do not need to, this change only provides debugging information.

**Comment by sbillard** [comment] 2018-02-06 19:12
Any update on this issue: has it occurred since you installed the debug code? If so I need to see the debug log.

**Comment by Elinth** [comment] 2018-02-06 19:16
Hi Stephen,
I have checked this daily and strangely enough no occurrence since the debug code yet..

**Comment by sbillard** [comment] 2018-02-14 00:24
Still no failures? You might as well upgrade to 1.5.3.03 to get the styleable login forms (#722.) I doubt the issue was caused by ZenPhoto since the debug code only checks if something has changed. with your agreement I will  close the issue. It can always be reopened if the issue comes back,

**Comment by Elinth** [comment] 2018-02-14 08:46
No failures, I was going to ask you the same thing. Let's close this issue.

**Comment by Elinth** [comment] 2018-02-14 08:57
After the upgrade to 1.5.3.03 (which is awesome!) my news settings are gone...

**Comment by sbillard** [comment] 2018-02-14 17:14
Did it happen when you ran the setup program?

**Comment by sbillard** [comment] 2018-02-15 01:32
Also, is there anything in the Debug Log?

**Comment by Elinth** [comment] 2018-02-16 08:53
Nothing in the Debug Log. Yes it happened right after the set-up program.Also the colorbox plugin was de-activated after set up. By the way, thank you so much for the changes on the styleable login forms! Brilliant!

**Comment by sbillard** [comment] 2018-02-16 15:03
I will make a release with the debug code as an option and post it here.

As to the colorbox disable. There was a theme (or more) that was permanently disabling colorbox. I don't remember at the moment which. This happened on setup, but was done by the theme's option constructor if I remember correctly. I don't remember the theme, and anyway, it has been fixed. Maybe you have still got that code somewhere.

**Comment by Elinth** [comment] 2018-02-16 16:01
Thanks!!

**Comment by sbillard** [comment] 2018-02-16 17:15
[setup-1.5.3.04.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1732153/setup-1.5.3.04.zip)

Enable the "debug" plugin and set the"log managed objects" option.

**Comment by sbillard** [comment] 2018-02-26 02:08
Any recurrence since version 1.5.3.9?

**Comment by Elinth** [comment] 2018-02-26 10:46
It's been stable. Let's close the issue.

**Comment by Elinth** [comment] 2018-03-02 08:47
Hi Stephen,

It happened again, can I email you the debug log?

**Comment by Elinth** [comment] 2018-03-02 09:05
Actually, I see nothing strange in the debug log. I do see this in the setup log: Setup found the field "truncation" in the "news" table. This field is not in use by ZenPhoto20.

**Comment by sbillard** [comment] 2018-03-02 15:09
Was the debug option still set? That would have logged any time that ZenPhoto20 changed the values. Did this happen again during a setup run? Anything else you can think of that might be in common with when this happens. Also check your server logs for the time around when the problem happened.

To provide a log (which probably will not be useful this time) you can zip it and attach it to your comments. See the bottom of the input box. Maybe just go ahead and attach it just in case.

You can either ignore the setup message or you can manually drop the "truncation" field. As said, ZenPhoto20 does not use it, but will leave it in place because it also did not create it.

**Comment by sbillard** [comment] 2018-03-04 23:13
[setup-1.5.3.16.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1779067/setup-1.5.3.16.zip)

This version has more debugging code. If it does not trap the situation then it must be outside of ZenPhoto20.

At any case, you will need to carefully monitor the situation so we know what might have been going on around the time of the failure.

**Comment by Elinth** [comment] 2018-03-06 17:27
Hi Stephen,
I will give this a try. Hope it traps what happened. I will keep an close eye on it.
Many Thanks!

**Comment by Elinth** [comment] 2018-03-06 17:38
What are the recommended settings for the debug plugin?

**Comment by sbillard** [comment] 2018-03-06 21:41
Just turn on the option Log Managed Objects changes option.

**Comment by Elinth** [comment] 2018-03-09 09:04
Hi Stephen, I just accidentally deleted the debug file, how can I get this back in the list?

**Comment by sbillard** [comment] 2018-03-25 23:57
[setup-1.6.0.03.zip](https://github.com/ZenPhoto20/ZenPhoto20/files/1845984/setup-1.6.0.03.zip)

**Comment by Elinth** [comment] 2018-03-27 15:13
Thanks!! no errors with the install 👍

**Comment by sbillard** [comment] 2018-03-27 18:42
Good news. This was a really haard problem to find. Thanks for your patience.

**Closed** 2018-03-27 19:55 UTC
Labels: bug
