### ISSUE TITLE
Imagemagick version > 3.0

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [ZenPhoto20/ZenPhoto20#612] opened 2017-06-07 10:16 UTC
I am deploying zenphoto 2.0 onto ubuntu 14.04 which the stock imagemagick is > 6.0 but zenphoto 20 does not allow me to turn it on claimed required imagemagick > 3.0

any idea how to overcome the issue?

**Comment by sbillard** [comment] 2017-06-07 14:10
There are two bits of software involved with Imagicmagic. One is the binary itself and one is the PHP support library. What is the exact message you get? If it is 

"The **_Imagick_** library version must be **3.0** or later" the issue is with the PHP support library.

**Comment by The-Edge-Malaysia** [comment] 2017-06-07 14:23
Thanks. Is the system php7 compatible? If so I may just upgrade the current
ubuntu 14.04 to 16.04

**Comment by sbillard** [comment] 2017-06-07 14:53
Yes, the system is PHP7 compatible. That is the version I test with.

**Comment by The-Edge-Malaysia** [comment] 2017-06-07 18:01
thanks, will upgrade accordingly

**Comment by sbillard** [comment] 2017-06-07 21:59
Ok, I will close this ticket. If you have further problems please open a new one.

**Comment by The-Edge-Malaysia** [comment] 2017-06-08 06:39
hi!

after upgraded to ubuntu 16.04 and with php7, the message "The Imagick
library version must be 3.0.0 or greater" still appear and the option is
disabled.

Any clue?

**Comment by sbillard** [comment] 2017-06-08 15:46
If you enable the _Debug_ plugin there will be a menu item under _Develpment_ for PHPINFO. There should be an entry in that data for the Imagick PHP library that will tell you what version it is. You may need to find an updated version of the PHP Imagick extension.

You can also insert `echo phpversion('imagick');` somewhere to print out the version of the library.

**Comment by sbillard** [comment] 2017-06-08 17:36
Turns out there has been a bug introduced. A fix will be available shortly.

**Closed** 2017-06-08 17:39 UTC

**Comment by sbillard** [comment] 2017-06-08 17:52
https://github.com/ZenPhoto20/ZenPhoto20/releases/download/ZenPhoto20-1.4.1.0/setup-1.4.1.7.zip

**Comment by The-Edge-Malaysia** [comment] 2017-06-09 04:21
Thanks!

It works!!
