### ISSUE TITLE
Phrases that are not translated or translated, but are displayed in English (not in Czech)

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#662] opened 2017-10-15 14:55 UTC
**Can´t translate:**
"Example" - plugin category, menu Plugin -> Example
"Theme" - plugin category, menu Plugin -> Theme

**Are translated but displayed in English:**
"Plugin setup:" - when installing gallery
"You can now administer your gallery." - when installing gallery
"The Setup environment is not totally secure, you should protect the scripts to thwart hackers. Protect the scripts."

**Comment by sbillard** [comment] 2017-10-15 18:07
The first two I have fixed. The translated but displayed in English are baffling.

Text before and after them are translated. Except for "Plugin setup:" they have some HTML imbedded in the string. I have made a version that does not do that in hope it will help. I have no clue about "Plugin setup:" there appears nothing unique about it.

**Comment by sbillard** [comment] 2017-10-16 00:36
Well, I have to say that none of this makes any sense. I can find two strings just a few lines apart in the code. One (sent to the web page) is translated correctly, one (sent to the setup log) is not translated. There seems to be no correlation on what works and what does not.

I did a web search on the issue and found some references to similar issues but no solutions so far as I could tell. One "answer" said that gettext() does not translate "fuzzy" strings, but some of the strings. ("plugin setup") are clearly not marked fuzzy.

Another said that apache "locale" settings are not reliable. But my local testing uses the php-gettext library since native gettext() does not work on my Windows WAMP server. This makes no use of apache.

I ran into some other non-translated strings that you did not note. For instance "Done with table update" (Since changed to "table update complete" which also fails!) I am using French for my testing since I understand it much better than Czech!

**Comment by Mates-K1** [comment] 2017-10-16 09:21
For me all those phrases work and are translated (after I updated my language files) now. :)

**Comment by Mates-K1** [comment] 2017-10-16 11:10
Another translated but not displayed:

_You have received this email because you registered with the user id %3$s on this site.
To complete your registration visit %1$s._

**Comment by Mates-K1** [comment] 2017-10-16 14:37
Cant translate:
"separator" - from theme setting

**Comment by sbillard** [comment] 2017-10-16 15:27
I am glad that the update causes the strings to translate. Just wish I understood what is happening. 

Of the new reported strings, the first one is another of those we don't understand. If the string shows up in your PoEdit editor, it is likely that it fits this category. The second is a missing ``gettext()` call that will be fixed shortly.

I've also updated the handling of the `getAllTranslations()` functions to comment out duplicates. Maybe that will fix the first string. (It is from the _allTranslations.php_ file.

**Comment by Mates-K1** [comment] 2017-10-16 19:26
I think you have a typo in the github fix text - isue 622 vs 662.


>  If the string shows up in your PoEdit editor, it is likely that it fits this category. The second is a missing ``gettext()` call that will be fixed shortly.

First isnt fix for me, second one works.

**Comment by sbillard** [comment] 2017-10-16 23:32
There does not seem to be any reasonable way to edit a commit message, so I guess the typo will just stay.

There is one thing you can try with the first message. Comment out the line with the message in getAllTranslations.php  Then update your PoEdit with the line missing, save the translation, then uncomment the line, update PoEdit, and save it again. Maybe that will 'shake" things up a bit and the translation will recover. But this is only a guess. We really do not know what the problem is.

I suspect that the issue is with PoEdit since I get the failures both with PHP gettext() and with the replacement library. Two different implementations are unlikely to have the same bug.

**Comment by Mates-K1** [comment] 2017-10-17 10:10
> Comment out the line with the message in getAllTranslations.php Then update your PoEdit with the line missing, save the translation, then uncomment the line, update PoEdit, and save it again.

Didnt help...

When I tried change and saved this form from backend, it changed my text back to predefined.

**Comment by sbillard** [comment] 2017-10-17 14:53
I am out of ideas, then. Maybe an update of PoEdit will come along. I think that must be the source of the problem. I will leave this issue open for now.

**Comment by sbillard** [comment] 2018-02-06 19:14
How did these translations work out with your last update?

**Comment by Mates-K1** [comment] 2018-02-06 20:31
> Are translated but displayed in English:
> "Plugin setup:" - when installing gallery
> "You can now administer your gallery." - when installing gallery
> "The Setup environment is not totally secure, you should protect the scripts to thwart hackers. Protect the scripts."

That´s OK as I wrote.

> Cant translate:
> "separator" - from theme setting

That´s OK too.

> You have received this email because you registered with the user id %3$s on this site.
> To complete your registration visit %1$s.

...from register_user plugin still display in english despite that is translated. But I can rewrite text and save it (I could not do it in October 2017).

**Comment by sbillard** [comment] 2018-02-06 20:36
Is it ok, then if I close this ticket? Certainly nothing in ZP20 has changed with respect to these items.

**Comment by Mates-K1** [comment] 2018-02-06 20:44
For me, this state is OK.
Thanks.

**Closed** 2018-02-07 00:17 UTC
Labels: bug
