### ISSUE TITLE
Effervescence+ theme - missing CSS?

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/ZenPhoto20#376] opened 2015-06-03 15:57 UTC
ZP20 1.1.7.12 - all files deleted and uploaded again
Can you confirm this bug on all pages in gallery?
![theme](https://cloud.githubusercontent.com/assets/7648991/7964739/b468eaac-0a19-11e5-892b-7c309d659767.jpg)

![theme1](https://cloud.githubusercontent.com/assets/7648991/7964767/df67c516-0a19-11e5-9ce9-ec855b7170ca.jpg)

**Comment by Mates-K1** [comment] 2015-06-03 16:08
And... zpskeleton too...

**Comment by sbillard** [comment] 2015-06-03 17:11
Did you run setup? If not you need to do so for EF+ to regenerate the CSS files.

**Comment by sbillard** [comment] 2015-06-03 17:23
I was not able to reproduce this. But maybe it is specific to the "theme colors". What are your options for the theme?

**Comment by sbillard** [comment] 2015-06-03 17:24
closed by mistake.

**Comment by Mates-K1** [comment] 2015-06-03 17:43
Yes, I did. I run setup always when I upgrade. Now I ran setup again - same problem.

All theme colors (rainbow,..) are affected.

![e1](https://cloud.githubusercontent.com/assets/7648991/7967130/9abcf6a2-0a28-11e5-8803-cf25f1eaa174.jpg)
![e2](https://cloud.githubusercontent.com/assets/7648991/7967131/9d4af338-0a28-11e5-8e42-13635ea3715d.jpg)
![e3](https://cloud.githubusercontent.com/assets/7648991/7967133/a075acb0-0a28-11e5-811c-241049e8f643.jpg)

**Comment by sbillard** [comment] 2015-06-03 17:58
Can't reproduce with Poolside either. 

Please look in your zp-data folder. There should be a subfolder named effervescence+ that contains the generated css files. If they do not exist there may be a permissions issue with the folder(s). If they do exist, what dates do they have? 

Also check your logs for any errors. And try setting the debug option to show 404 errors. (Enable the debug plugin and set this in its options, then enable it with the Mark Release button.)

If all else fails, clear your browsers cached files, maybe it is getting confused since the css files will have been renewed.

**Comment by Mates-K1** [comment] 2015-06-03 18:28
There are CSS files in zp-data. Their dates are actual (about hour ago).

Errors in backend:
Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php:387) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-basic.php on line 1578

Warning: Cannot modify header information - headers already sent by (output started at /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php:387) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/admin-functions.php on line 106

Warning: Cannot modify header information - headers already sent by (output started at /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php:387) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/admin-functions.php on line 107

Errors in frontend:
Notice: Use of undefined constant LOCAL_CHARSET - assumed 'LOCAL_CHARSET' in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387

Warning: html_entity_decode() [function.html-entity-decode]: charset `LOCAL_CHARSET' not supported, assuming iso-8859-1 in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php on line 387


Clearing browser cache didnt help.

**Comment by Mates-K1** [comment] 2015-06-03 18:31
I clicked Mark as release again and whole backend crashed. :)
With all errors above +

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php:387) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-basic.php on line 1578

Warning: Cannot modify header information - headers already sent by (output started at /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/functions-common.php:387) in /net/home/skaut.zamberk.cz/html/galerieonline/zp-core/zp-extensions/debug.php on line 44

**Comment by sbillard** [comment] 2015-06-03 20:50
All these problems stem from the error "Use of undefined constant LOACL_CHARSET". Unfortunately, I think that must be a symptom of some other problem since I have never seen the error in any of my testing.

Is it possible for you to set up your PHP to provide a stack trace on errors? Then we can find the sequence that causes this error. In the mean time, I can make a workaround that avoids the error. https://github.com/sbillard/ZenPhoto20-DEV/

Do any other themes have CSS issues?

**Comment by Mates-K1** [comment] 2015-06-03 21:57
Sorry, PHP and me - we are not friends. :) Is it some specific function? - I will ask my provider to set it on.

This bug is only in Effervescence+.

**Comment by sbillard** [comment] 2015-06-03 22:23
It is a special configuration of PHP. Maybe just try the workaround first. If that works, great. If not I can make a debug install that will give me the needed data.

**Comment by Mates-K1** [comment] 2015-06-03 23:04
I tried latest ZP20DEV, there is no error (debug on and Mark release), but Effervescence+ theme is still broken. :(

(ran setup, clear browser cache,...)

**Comment by sbillard** [comment] 2015-06-03 23:48
Does http://testalbum.sbillard.org/?themeSwitcher=effervescence%2B look correct on your browser?

**Comment by Mates-K1** [comment] 2015-06-04 06:18
Yes, test album looks correct (Chrome, IE, FF).

When I delete CSS and switch to Effervescence+, ZP20 dont create new CSS files.

Files arent create even after running setup.

**Comment by Mates-K1** [comment] 2015-06-04 06:28
Mistake - when I change theme to Effervescence+, it creates CSS files.

**Comment by sbillard** [comment] 2015-06-04 16:38
I presume that the CSS is still not loading? Perhaps you can setup a clone install with effervescence+ set as the theme so I can view the site. Maybe that will give some clues. Also maybe there are other logs to look at, sometimes there is a separate Apache log that shows things like what files are loaded. It might show something.

**Comment by Mates-K1** [comment] 2015-06-05 12:31
Yes, CSS in not loading.

I will send you email with login to test gallery - fresh install, fresh DB - Effervescence+ still without CSS.

**Comment by Mates-K1** [comment] 2015-06-05 12:44
And... CSS files are generated sucesfully in zp-data...

**Comment by sbillard** [comment] 2015-06-05 23:07
I am unable to discover what is preventing these CSS files from loading. I have tried multiple things--I even created an effervescence2 theme which unfortunately I cannot now delete just in case the plus sign was the issue. It was not.

From what I can tell, the plus sign is not an issue. The effervescence+/common.css file gets successfully loaded. So the only thing I can think of is that there is some kind of restriction on your zp-data folder or one of the effervescence+ folders under it. 

Your host server logs may have some information if you can find all of them. Specially the Apache access log. You should see something similar to `GET /test_sites/dev/zp-data/effervescence+/styles/see%20you%20again.css HTTP/1.1" 200 21172`

**Comment by Mates-K1** [comment] 2015-06-06 08:34
Ok, I will get log. I wrote to my provider (I cant see logs for this domain).

**Comment by sbillard** [comment] 2015-06-06 17:09
I have another thought. Perhaps this is some kind of security software permissions issue. Please look at the file permissions for the common.css file in the effervescence+ theme folder. Compare that with the permissions of the css files in the zp-data folder. If they are different, change the ones in the zp-data folder to match the common.css permissions and let me know what the values are.

**Comment by Mates-K1** [comment] 2015-06-06 20:13
common.css has 0644 permision.
CSS in zp-data has 0644 too.

**Comment by Mates-K1** [comment] 2015-06-06 20:47
For CSS in zp-data Firefox says:

500 Internal Server Error
Apache Server at skaut.zamberk.cz Port 80

**Comment by sbillard** [comment] 2015-06-06 20:51
Ok, you will have to discuss with your host what is causing that Internal Server Error. It is probably somewhere in the Apache logs.

**Comment by Mates-K1** [comment] 2015-06-06 21:05
Is problem in .htaccess in zp-data?
When I rename it, theme works.

.htacess in zp-data:
![web](https://cloud.githubusercontent.com/assets/7648991/8021454/8a0dddb0-0ca0-11e5-8a48-e0eb2a90ebe3.jpg)

**Comment by sbillard** [comment] 2015-06-06 22:34
Good progress!

But there is nothing wrong with the .htaccess file, so we still do not know why it fails on your installation.

What the file should be doing is denying access to files with the suffixes .htaccess, .cfg, .log, and .php. So css files should be allowed. Also it should be causing a 403-forbidden result, not a 500-server error.

So maybe try some things and report back what works. 

First, remove the whole `<FilesMatch...> </FilesMatch>` part. That should just prevent browsers from listing the zp-data directory. If that works, then remove just the line that says `Order Allow,Deny` That line should be redundant anyway.

The only other solution will be to move those css files. I did not want to do that because it there is no good place to place them. If in the normal effervescence+ folder they will appear as "extra" files to setup. Even if we teach setup about them if someone makes a custom themecolor that would have to go in the same place and would cause the appearance of an extra file.

**Comment by Mates-K1** [comment] 2015-06-06 22:56
Removing whole part works, removing only one row didnt work.

**Comment by sbillard** [comment] 2015-06-06 23:16
Ok, that is an error somehow with your server, but I have figured out a way to relocate the files. Please try the ZenPhoto20-DEV build and let me know if it works for you.

**Comment by Mates-K1** [comment] 2015-06-06 23:46
Yes, it works. :)

**Closed** 2015-06-07 00:10 UTC

**Comment by Mates-K1** [comment] 2015-06-10 11:40
Still need access log? Now I have access to log, but it is genereated every twice a month (1. and 15.) - we need log from 5. and 6. 6.

**Comment by Mates-K1** [comment] 2015-06-10 12:01
Edit: I have access log. See mail...

**Comment by sbillard** [comment] 2015-06-10 16:03
Thanks for the access log. It does not add anything new. For some reason the .htaccess in the data folder is not working correctly. That is a server issue and can cause you other problems, but the change to the CSS file location has made ZenPhoto20 work correctly, so not necessarily an issue for us.

**Comment by Mates-K1** [comment] 2015-06-10 16:28
Ok.., I´ll think about it if another error occurred on my site in future.
